<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudServices.Domain\CloudServices.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviours\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Features\" />
  </ItemGroup>

</Project>
