import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
<<<<<<< Updated upstream:frontend/cloud-services-web/src/app/(public)/layout.tsx
import { Toaster } from "@/components/ui/toast";
=======
<<<<<<< Updated upstream:frontend/cloud-services-web/src/app/layout.tsx
=======
import { Toaster } from "@/components/ui/toast";
import { SessionProvider } from "next-auth/react";
>>>>>>> Stashed changes:frontend/cloud-services-web/src/app/(public)/layout.tsx
>>>>>>> Stashed changes:frontend/cloud-services-web/src/app/layout.tsx

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cloud Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
<<<<<<< Updated upstream:frontend/cloud-services-web/src/app/layout.tsx
        <Header />
        {children}
        <Footer />
<<<<<<< Updated upstream:frontend/cloud-services-web/src/app/(public)/layout.tsx
        <Toaster />
=======
=======
        <SessionProvider>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </SessionProvider>
>>>>>>> Stashed changes:frontend/cloud-services-web/src/app/(public)/layout.tsx
>>>>>>> Stashed changes:frontend/cloud-services-web/src/app/layout.tsx
      </body>
    </html>
  );
}
