name: .NET Core CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests with coverage
      run: dotnet test --no-build --configuration Release --settings CloudServices.UnitTests/.runsettings --collect:"XPlat Code Coverage"

    - name: Generate Code Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;HtmlSummary;TextSummary'

    - name: Upload Test Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coveragereport/
        retention-days: 7
